# Generated by Django 4.2.5 on 2023-09-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('users', '0002_siteuser_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='subscription',
            field=models.CharField(choices=[('FR', 'Бесплатная'), ('BS', 'Базовая'), ('GD', 'Золотая')], default='FR', max_length=2, verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='preferences', to='recipes.category', verbose_name='Предпочтения'),
        ),
    ]
