# Generated by Django 4.2.5 on 2023-09-19 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('users', '0003_siteuser_subscription_alter_siteuser_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('L', 'Лайк'), ('D', 'Дизлайк')], default='L', max_length=1, verbose_name='Голос')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_voted', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_recepies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
