# Generated by Django 4.2.5 on 2023-09-20 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_siteuser_subscription_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription',
        ),
        migrations.AddField(
            model_name='subscription',
            name='duration_months',
            field=models.IntegerField(choices=[(1, 'Один'), (3, 'Три'), (6, 'Шесть'), (12, 'Двеннадцать')], default=1, verbose_name='Тип подписки'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала подписки'),
        ),
    ]
