# Generated by Django 4.2.5 on 2023-09-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_siteuser_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration_months',
            field=models.IntegerField(choices=[(1, 'Один месяц'), (3, 'Три месяца'), (6, 'Шесть месяцев'), (12, 'Двеннадцать месяцев')], default=1, verbose_name='Тип подписки'),
        ),
    ]
