# Generated by Django 4.2.5 on 2023-09-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_subscription_duration_months'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='categories',
            new_name='allergies',
        ),
    ]
