# Generated by Django 4.2.5 on 2023-09-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_allergy',
            field=models.BooleanField(default=False, verbose_name='Аллергия'),
        ),
    ]
